version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'in_range'
      - match:
          dependency_type: 'production'
          update_type: 'security:patch'
    ignored_updates:
      - match:
          dependency_name: 'aws-sdk'
